#if defined _pt_sc_assert_inc
    #endinput
#endif
#define _pt_sc_assert_inc

#include <pawntest/scenarios/player>
#include <pawntest/scenarios/vehicle>
#include <pawntest/scenarios/object>
#include <pawntest/scenarios/actor>
#include <pawntest/scenarios/pickup>
#include <pawntest/scenarios/checkpoint>
#include <pawntest/scenarios/textlabel>
#include <pawntest/scenarios/textdraw>
#include <pawntest/scenarios/gangzone>
#include <pawntest/scenarios/dialog>
#include <pawntest/scenarios/menu>
#include <pawntest/scenarios/class>
#include <pawntest/scenarios/variable>
#include <pawntest/scenarios/server>
#include <pawntest/scenarios/npc>
#include <pawntest/scenarios/database>
#include <pawntest/scenarios/http>
#include <pawntest/scenarios/event>
